export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as MobileMenu } from './MobileMenu'
export { default as Skills } from './Skills'
export { default as Spinner } from './Spinner'
export { default as Work } from './Work'